name: Build on Tag

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: wolverine998/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: RN9ProQualcomm
      with:
        arch: arm64
        compiler: proton-clang/master
        defconfig: vendor/xiaomi/miatoll_defconfig
        image: Image.gz

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: "zipper/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
